### ISSUE TITLE
cannot switch bw tab A and tab B after I put my macbook to sleep

### ISSUE THREAD

**Issue by avalanche1** [orschiro/switch-recent-tabs-chrome-extension#19]
After last update of my browser (or the extenstion - they seemed to happen at the same time, start of March) extenstion functionality seem to be broken in tf way:

- chrome is open on tab A; extension can switch bw tab A and tab B
- I put my macbook to sleep
- I wake it
- chrome is still open on tab A
- the extenstion doesnt work - it cannot switch bw tab A and tab B (pressing alt-q does nuttin)
- now, in order to make it work I have to go to tab B manually

Before the update it worked seamlessly, no matter how many times I closed the lid of my macbook

**Comment by orschiro** [comment]
@avalanche1 does it work if you click on the toggle button/icon?

**Comment by orschiro** [comment]
Labelled as bug for further triaging.

**Comment by menocomp** [comment]
It worked correctly with me after remove keyboard binding and add it again. https://github.com/orschiro/tsrlt-chrome-extension/wiki/FAQ

**Comment by orschiro** [comment]
@menocomp thanks for confirming! Closing this. Please always check the Wiki FAQ.

**Comment by avalanche1** [comment]
@menocomp 's advice didnt help. But reinstalling the extension alleviated the issue. It even miraculously works in chrome webstore - which it didnt do before.
I suggest to add a note to the faq: "If you experience problems with switching tabs - remove and install the extension anew"

**Comment by orschiro** [comment]
@avalanche1 added your note to the [wiki](https://github.com/orschiro/switch-recent-tabs-chrome-extension/wiki/FAQ), thanks!
