### ISSUE TITLE
Cannot toggle between tabs after closing an open tab

### ISSUE THREAD

**Issue by davzhou** [orschiro/switch-recent-tabs-chrome-extension#20]
I am currently using Chrome and a keyboard shortcut to toggle tabs. If I'm toggling between tab A and tab B and I open new tab C then immediately close it, I can no longer toggle between tab A and tab B. 

I remember it used to work but recently stopped working.

If i click on the icon nothing happens, but if I use the button in the dropdown the closed tab will reopen. That's not the behavior I was expecting or hoping for. I want the last viewed and open tab to be toggled to.

**Comment by orschiro** [comment]
Thanks @davzhou labelled as enhancement. It used to be a feature. I removed it to revert to the original functionality of this extension (toggle only between two tabs. Nothing more, nothing less).

**Comment by frankyjuang** [comment]
@davzhou can you confirm that this is solved after updating to ver.9

**Comment by orschiro** [comment]
@davzhou for me it's working and remembering the last tab before the two recent tabs, for what it's worth.

**Comment by davzhou** [comment]
Yup, looks good, thanks!
