### ISSUE TITLE
Deprecated Chrome APIs

### ISSUE THREAD

**Issue by frankyjuang** [orschiro/switch-recent-tabs-chrome-extension#21]
[`chrome.tabs.getSelected`](https://developer.chrome.com/extensions/tabs#method-getSelected),
 [`chrome.tabs.onSelectionChanged`](https://developer.chrome.com/extensions/tabs#event-onSelectionChanged) are both deprecated.

Is this extension actively maintained? If not, I would like to help maintain it since I have used it for quite a while but it's getting old and malfunctioned

**Comment by orschiro** [comment]
Dear @frankyjuang 

Would very much appreciate your help maintaining this extension!

I added you to the list of collaborators with push access. 

Are there any features you think should become default?

I removed some in the last update to keep things simple and clean but realised a lot of people are missing them. Now it's too simplistic. See for instance https://github.com/orschiro/switch-recent-tabs-chrome-extension/issues/20

Let me know.

Thanks!

**Comment by frankyjuang** [comment]
Thanks for adding me. 
I think __always__ being able to switch between the last two used tabs is necessary even after tab closed. 
Cross window switch would be a good plus. 
Keep it light weight and using up-to-date api are the must. 
That's all I have in mind right now.
I'll first make a PR for updating APIs.

What did you removed recently?

**Comment by orschiro** [comment]
> I think always being able to switch between the last two used tabs is necessary even after tab closed.

Yes, I think you convinced me.

> Cross window switch would be a good plus.

Yep, marked as enhancement: https://github.com/orschiro/switch-recent-tabs-chrome-extension/issues/17

> Keep it light weight and using up-to-date api are the must.
> That's all I have in mind right now.
> I'll first make a PR for updating APIs.

Thanks for your pull request!

> What did you removed recently?

I removed a lot of old code that was related to an option page we once had but that's no longer necessary. Better to provide sane defaults out of the box.

**Comment by frankyjuang** [comment]
So, should we add cross window support as default?

**Comment by orschiro** [comment]
@frankyjuang I went through the user feedback one more time and it is a highly requested feature. 

Hence I would opt in here, yes, to make it default.

Do you have an idea how to implement it?

**Comment by frankyjuang** [comment]
Great! Yay, I think we'll need a listener for change focus of windows. I remember that `onActivated` isn't triggered when switching windows. I'll try to make a PR for this in days.

**Comment by frankyjuang** [comment]
Issue addressed. Open another for discussing new features if needed.
