### ISSUE TITLE
Weird tab behaviour if once switch to other windows

### ISSUE THREAD

**Issue by orschiro** [orschiro/switch-recent-tabs-chrome-extension#24]
@frankyjuang just found the following tab behaviour:

https://youtu.be/RVgk8TqR0RI

Doesn't happen always. Can you reproduce it?

**Comment by orschiro** [comment]
Potentially related to introducing the history array, after a while it just stops completely for me to switch between tabs. I need to re-enable the extension to restore the functionality. Can you confirm?

**Comment by frankyjuang** [comment]
Can you confirm that it only happens if you once switch to another window?

**Comment by orschiro** [comment]
@frankyjuang correct! The tab inconsistency seems to be related to switching to another window.

**Comment by frankyjuang** [comment]
Track this issue at #17.
