### ISSUE TITLE
Chrome close tab behavior is changed

### ISSUE THREAD

**Issue by rscottfree** [orschiro/switch-recent-tabs-chrome-extension#25]
Closing a chrome tab usually takes me to the tab right next to the one I closed, but with this extension enabled it takes me to the most recent tab I was on as if I had clicked the button or used the keyboard shortcut to switch to the more recently used tab.

For example
There are 4 tabs, A B C D

1. I select tab A
2. I select tab D
3. I close tab D
4. I'm taken to tab A
5. (I expect to be taken to tab C)

This used to be working correctly until a recent update to Chrome or the extension, I don't know which. I've tried removing and re-installing the extension. I'm on Chrome 65.0.3325.146 and version 9 of the plugin.

If this is a change to how the extension works and it was intended, I'd prefer to have an option to disable it.

**Comment by orschiro** [comment]
@frankyjuang this behaviour got now introduced since we switch back to the third tab in a row.

What do you think? Shall we provide an option or make that up to other extension to cover where focus is placed on close?

**Comment by frankyjuang** [comment]
I think we can keep such tiny option. It wont bother to stay in the contextmenu of browser action. Just a checkbox, for exmaple
![image](https://user-images.githubusercontent.com/6175880/37242740-76b6d4fa-24a9-11e8-8c0b-2638e1ad2ed7.png)

What do you think?

**Comment by orschiro** [comment]
@frankyjuang I didn't know it was possible to place a checkbox in the context menu! Brilliant idea. That makes it possible not maintaining a separate options page.

**Comment by firesofmay** [comment]
I agree with this issue, recent issue is very annoying. I had to disable all extensions to figure out which extension is causing this issue. It would be great if we can restore the tab close behaviour to default behaviour.

**Comment by orschiro** [comment]
@firesofmay this is coming with the next version 10 to be released today or tomorrow!

**Comment by rscottfree** [comment]
Version 10 has fixed this issue for me. Thank you! 🙏

**Comment by orschiro** [comment]
Thanks for your feedback and testing @rscottfree !

**Comment by firesofmay** [comment]
Thanks it worked!

**Comment by orschiro** [comment]
@firesofmay glad to hear! @frankyjuang really did amazing work here. Thank you!
