### ISSUE TITLE
Donations February 2018

### ISSUE THREAD

**Issue by orschiro** [orschiro/switch-recent-tabs-chrome-extension#29]
@frankyjuang for February 2018, we got 3€ in donation. Any preference on to whom to donate? :-)

![image](https://user-images.githubusercontent.com/170947/37403328-bac21f64-278e-11e8-862b-09ed8c61ce82.png)

**Comment by frankyjuang** [comment]
Interesting! 50-50 is fine with me 😃

**Comment by orschiro** [comment]
I can make it over to your PayPal and then you decide yourself :)

What's your PayPal?

**Comment by frankyjuang** [comment]
[YLJuang](https://www.paypal.me/YLJuang)
Not sure if the name is displayed in chinese 莊​佾霖 😆

**Comment by orschiro** [comment]
Just sent you the money! :-)
