### ISSUE TITLE
Notify changelog

### ISSUE THREAD

**Issue by frankyjuang** [orschiro/switch-recent-tabs-chrome-extension#32]
As mentioned at #31, notify users about new feature. Otherwise, they won't know the there's an update and now can use multiple windows.
`chrome.runtime.onInstalled.addListener(function callback)` is fired when extension is installed or update.

**Comment by frankyjuang** [comment]
@orschiro any ideas how the notification will look like?

**Comment by orschiro** [comment]
@frankyjuang I would just go for the default notification look with a basic message "You just update to version 11 which supports multiple windows :-)"
