### ISSUE TITLE
It does not work now after the auto update

### ISSUE THREAD

**Issue by CicoZhang** [orschiro/switch-recent-tabs-chrome-extension#37]
It does not work any longer after today's automatic update. Please fix it! Thanks in advance.

**Comment by orschiro** [comment]
@CicoZhang please help us debugging:

https://github.com/orschiro/switch-recent-tabs-chrome-extension/wiki/FAQ#help-us-debugging

**Comment by orschiro** [comment]
Duplicate of #17
